### ISSUE TITLE
我复制了DialogDemo，但是Global/Local没有效果。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#161]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/de94b2f7-7484-4a90-a24d-ca01363f54f9)
能正常显示。
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/f4d978a5-84c2-41b4-9157-c90649a593c9)
不显示弹窗，没有效果。

**Comment by rabbitism** [comment]
全局需要自己放置一个OverlayDialogHost，Ursa demo里面我是放在了main view里面的

**Comment by YSW33** [comment]
> 全局需要自己放置一个OverlayDialogHost，Ursa demo里面我是放在了main view里面的
解决了，非常感谢。
