### ISSUE TITLE
安卓13，OverlayDialog 有肉眼可见的跳帧，Desktop下面第一次有跳帧，再次打开就十分流程。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#163]
1. 处理器：高通骁龙695
2. 运行内存 8GB+2GB
3. 安卓：13
4. MagicOS 7.0
6. windows子系统
7. 6GB

**Comment by rabbitism** [comment]
我是不是应该加一个禁用动画的选项呢？目前mask和DIalog本身都是通过动画入场的。

**Comment by YSW33** [comment]
可以加个，动画其实还蛮耗费资源的。
