### ISSUE TITLE
LoadingContainer 能使dialog右上角关闭按钮失效吗？

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#164]

**Comment by YSW33** [comment]
另外使用了LoadingContainer ，控件的宽和高都被压缩了，LoadingContainer 可以自适应控件大小吗？

**Comment by rabbitism** [comment]
1 no，dialog默认的关闭按钮永远处于最上层。但你可以通过options来隐藏默认按钮，在自己的dialog view上加个关闭按钮自己控制关闭行为
2 尝试设置container的alignment和content alignment

**Comment by YSW33** [comment]
> 1 no，dialog默认的关闭按钮永远处于最上层。但你可以通过options来隐藏默认按钮，在自己的dialog view上加个关闭按钮自己控制关闭行为 2 尝试设置container的alignment和content alignment

OK，我去试试

**Comment by YSW33** [comment]
ShowCloseButton和IsCloseButtonVisible 置成 false都无效，是不是我用错了参数。

**Comment by rabbitism** [comment]
> ShowCloseButton和IsCloseButtonVisible 置成 false都无效，是不是我用错了参数。

ShowCloseButton是仅对ShowCustom有效的，这个我在xml doc中已经写了。
![image](https://github.com/irihitech/Ursa.Avalonia/assets/14807942/f013732b-6852-485d-9580-ba4b0bd96d41)

**Comment by YSW33** [comment]
OK，搞定了，3Q~
