### ISSUE TITLE
Linux Pagination问题 

### ISSUE THREAD

**Issue by jia1025661679** [irihitech/Ursa.Avalonia#165]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/27859444/1c5732a9-c679-451f-b5d6-79e05bcbc30b)
Linux下窗口最大化时选择每页数量时显示错位

**Comment by rabbitism** [comment]
这只是一个正常的combobox。其他combobox会有问题吗？

**Comment by jia1025661679** [comment]
这个不知道是不是我虚拟机的原因，我在虚拟机全屏状态下显示会这样但是我退出全屏正常的去最大化窗口时他又不这样了

**Comment by rabbitism** [comment]
我并不能做什么，因为我只是用了ComboBox，这不是Pagination的问题~
