### ISSUE TITLE
代码中没有 标识符 AllowBinarySpecifier，但是界面启动后有这个标识符

### ISSUE THREAD

**Issue by heartacker** [irihitech/Ursa.Avalonia#174]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/1876302/e067c3ed-9657-45be-a25d-4fc7c0767764)

![image](https://github.com/irihitech/Ursa.Avalonia/assets/1876302/4d279423-1996-4dd9-93a1-2cdc27ffe7ea)

**Comment by rabbitism** [comment]
很有可能是因为ursa是standard2.0但demo是net8

**Comment by rabbitism** [comment]
很有可能是因为ursa是standard2.0但demo是net8

**Comment by rabbitism** [comment]
Closed by #175
