### ISSUE TITLE
Browser中文显示是乱码，DEMO里面也是乱码。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#177]

**Comment by rabbitism** [comment]
因为我们为了让仓库体积小一些所以没有内嵌字体。

**Comment by YSW33** [comment]
> 因为我们为了让仓库体积小一些所以没有内嵌字体。

按照官方的操作，每个控件都要加个FontFamily，这个就比较蛋疼了，有别的办法没？
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/6133238f-fbde-4edc-925e-24dcd01c8152)
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/cab1a442-c9d6-452f-88bc-443acee15eec)

**Comment by YSW33** [comment]
能提供一个统一设置FontFamily的接口吗？

**Comment by YSW33** [comment]
APP里面设置全局也只有Android、Desktop有效，Browser无效。
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/1b4b4ff1-5150-4b13-af0c-649f1635df0e)

**Comment by zdpcdt** [comment]
你可以看看font分支，这个分支内嵌了字体的

**Comment by YSW33** [comment]
> 你可以看看font分支，这个分支内嵌了字体的

非常感谢，解决了！
