### ISSUE TITLE
ADD numericalupdown Command SUPPORTED

### ISSUE THREAD

**Issue by heartacker** [irihitech/Ursa.Avalonia#179]
FOR mvvm

**Comment by heartacker** [comment]
@rabbitism 兔大，我不是熟悉如何添加  command 的支持，只是会简单的使用。
你可以方便一起弄一个demo 之类的吗？感谢啊
numericalupdown
1. 支持 command 绑定
2. command 默认传递的参数是 value，
3. 或者人为支持 设定绑定 command  的参数，
4. 其实我不懂得方面

**Comment by rabbitism** [comment]
刚好 PR #182 就是在做这个事情，建议参考一下。

**Comment by heartacker** [comment]
Review please. :D
