### ISSUE TITLE
OverlayDialog.ShowCustomModal 设置居中，左边及上边始终比右边和下面要多几个像素。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#181]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/bc65c249-5819-49fd-b9ff-8e277f529503)

**Comment by YSW33** [comment]
Result = await OverlayDialog.ShowCustomModal<LoginControl, LoginViewModel, bool>(
            vm, true ? null : "LocalHost", options: new OverlayDialogOptions()
            {
                ShowCloseButton = false,
                CanLightDismiss = CanLightDismiss,
                HorizontalOffset = 0,
                VerticalOffset = 0,
                HorizontalAnchor = HorizontalPosition.Center,
                VerticalAnchor = VerticalPosition.Center,
            });

**Comment by YSW33** [comment]
安卓界面更加明显
![160283ae5d5952b6259e5dbb7d4a69c](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/c0315ee8-3420-4f51-959f-713b77233ff8)

**Comment by rabbitism** [comment]
dialog有8 margin用于渲染阴影

**Comment by YSW33** [comment]
> dialog有8 margin用于渲染阴影

也就是我减去16就没问题了对吧。

**Comment by YSW33** [comment]
> dialog有8 margin用于渲染阴影

除掉上下左右8margin，左、上比右、下肉眼目测还是多大概2-3的样子.
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/559c8132-9200-4221-8d13-eff87eff1c41)

**Comment by rabbitism** [comment]
看了一下，margin是10。可能宽度要减20了。

**Comment by YSW33** [comment]
> 看了一下，margin是10。可能宽度要减20了。
减去20就正常了，能不能提供一个阴影开关的参数，dialog移动端直接用来打开功能界面还是挺方便的。
