### ISSUE TITLE
numericupdown 当 删除text box 的text 之后，直接 点击spinner 会报错

### ISSUE THREAD

**Issue by heartacker** [irihitech/Ursa.Avalonia#189]

**Comment by rabbitism** [comment]
expected，当你文字都已经被删除了，我up应该从哪里up呢？所以我们提供了EmptyInputValue，用以表示当文字为空的时候应该回落到哪个默认值。

**Comment by heartacker** [comment]
> expected，当你文字都已经被删除了，我up应该从哪里up呢？所以我们提供了EmptyInputValue，用以表示当文字为空的时候应该回落到哪个默认值。

我认为，当用户在更改Textbox的内容
如增、删、清除 Text，都算是正在编辑
那么应该禁用用户点击其他updown。UI 确保不会出现错误。
