### ISSUE TITLE
PDA的红外线扫描会触发IconButton的Command。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#196]
1. 如果首次界面没有文本框等可以输入的控件，则不会弹出软键盘，并且Command不会被触发。
2. 打开一个带有输入框的界面，软键盘会弹出。
3. 接下来无论切换到什么界面，Button控件的Command都会随着红外扫描触发，并且软键盘一同弹出。

**Comment by rabbitism** [comment]
这些听起来都不是和Ursa相关的问题啊，换成普通Button呢？

**Comment by YSW33** [comment]
> 这些听起来都不是和Ursa相关的问题啊，换成普通Button呢？

一样触发。

我在MainActivity里面，通过设置Window.AddFlags(WindowManagerFlags.AltFocusableIm)禁用了软键盘，才不会触发，这就挺难受的。

**Comment by YSW33** [comment]
Avalonia 11.0.7，PDA使用红外扫描会触发button的Commnd，通过禁用软键盘可以解决触发问题。

在BaseActivity里禁用软键盘
getWindow().addFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
 
在需要打开的Activity取消禁用软键盘
getWindow().clearFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
