### ISSUE TITLE
Preprocessing the dialog when OK button clicked.

### ISSUE THREAD

**Issue by dameng324** [irihitech/Ursa.Avalonia#197]
I show the Dialog to let user input some data, but I cannot check the input and show error to user when they click `OK` button.

So I want show handle the `OK Command` before close the dialog.

Use the custom dialog will not work as I cannot close the dialog in my viewmodel when the check is passed.

so add a event options like `HandlingOKFunc` will be very helpfull, which can return a `Handled` value to prevent dialog closing.

So the cancel/yes/no button's command should has a same event?

What is the Ursa team's idea?

**Comment by rabbitism** [comment]
Why, custom dialog should work, just call RequestClose.Invoke(your result) after your validation succeeded.

**Comment by dameng324** [comment]
I found `IDialogContext` interface finally. It should work for me. Thanks.
