### ISSUE TITLE
希望对Form能支持自动创建表单，DataGrid也能自动创建数据

### ISSUE THREAD

**Issue by yangf85** [irihitech/Ursa.Avalonia#205]
这样应该能省很多事。。
提供一个特性，可以用在ViewModel上，比如Postion，Label，还有可以选择控件的类型，比如bool类型，可以是checkbox,也可以是switch。 如果是枚举，提供一个combobox，如果枚举有Flags ，那么combobox能够多选

**Comment by rabbitism** [comment]
DataGrid本来就支持AutoGenerateColumns. 
对于Form，你可以使用PropertyGrid https://github.com/bodong1987/Avalonia.PropertyGrid.
