### ISSUE TITLE
Drawer 在移动设备上面也有明显的跳帧。

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#213]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/4f77c757-a53b-41de-96a1-fe1a4657ba31)

**Comment by YSW33** [comment]
![b0337d3b308ecb56de79c9c662870de](https://github.com/irihitech/Ursa.Avalonia/assets/141573398/ee282fc7-0fcd-4984-9b6c-61f35db09bf5)

**Comment by rabbitism** [comment]
只是用了正常的Avalonia动画，如果卡顿的话那我也无能为力
