### ISSUE TITLE
EnumSelector控件的HorizontalAlignment布局出错。

### ISSUE THREAD

**Issue by WCKYWCKF** [irihitech/Ursa.Avalonia#223]
当EnumSelector的HorizontalAlignment="Stretch"时，EnumSelector的效果是HorizontalAlignment="Center"而不是正常的HorizontalAlignment="Stretch"。
效果如下：
![image](https://github.com/irihitech/Ursa.Avalonia/assets/82446104/1a202958-54ee-4b03-aacd-37c42629ffcf)

**Comment by rabbitism** [comment]
有可能只是因为我设置了一个默认的100宽度，你设置成Width="{x:Double.NaN}" 应该就可以了。

**Comment by WCKYWCKF** [comment]
问题已解决，不过当Width="NaN" 时，EnumSelector的HorizontalAlignment="Center"的话会使得EnumSelector无法显示。哈哈哈，希望越来越好！

**Comment by rabbitism** [comment]
> 问题已解决，不过当Width="NaN" 时，EnumSelector的HorizontalAlignment="Center"的话会使得EnumSelector无法显示。哈哈哈，希望越来越好！

这种情况可以设置个minwidth
