### ISSUE TITLE
我仿照ursa代码使用了OverlayDialog.ShowCustomModal，使用PDA扫描会不停触发调用OverlayDialog这个按钮的Command

### ISSUE THREAD

**Issue by YSW33** [irihitech/Ursa.Avalonia#225]
[BAP.Universal.Desktop.zip](https://github.com/irihitech/Ursa.Avalonia/files/15071093/BAP.Universal.Desktop.zip)
这是测试代码。
当我打开扫描验证的窗体，然后使用PDA的红外扫描功能，结果就不停的触发ModuleViewModel.OnItemActivate。
不知道是AVALONIA的问题还是OverlayDialog导致的。

**Comment by rabbitism** [comment]
之前不是有扫描反复触发按钮的问题么，感觉是同一个问题？

**Comment by YSW33** [comment]
> 之前不是有扫描反复触发按钮的问题么，感觉是同一个问题？

好像不是我遇到的，这个问题是最近才发现了。

**Comment by rabbitism** [comment]
我们并没有可以扫描的设备，你用的是什么呀，如果便宜我们也搞一个

**Comment by YSW33** [comment]
> 之前不是有扫描反复触发按钮的问题么，感觉是同一个问题？


> 我们并没有可以扫描的设备，你用的是什么呀，如果便宜我们也搞一个

我用的优博讯I6310，大概1400左右一个，还是个安卓7.0的，不知道安卓10会不会有这个问题，我还在找机器测试。

**Comment by YSW33** [comment]
> 我们并没有可以扫描的设备，你用的是什么呀，如果便宜我们也搞一个

CommunityToolkit.Mvvm 应该不会接收到安卓的消息吧。

**Comment by YSW33** [comment]
> 我们并没有可以扫描的设备，你用的是什么呀，如果便宜我们也搞一个

目前问题定位到了CommunityToolkit和AVALONIA，应该跟URSA没关系。

**Comment by YSW33** [comment]
问题处理掉了，ReactiveCommand.Create不会触发，RelayCommand会触发。
总之功能问题解决了，CommunityToolkit这个怎么解决还是不清楚……
