### ISSUE TITLE
OverlayDialog 内容超出边界

### ISSUE THREAD

**Issue by nblfeng** [irihitech/Ursa.Avalonia#237]
![Snipaste_2024-05-11_15-49-13](https://github.com/irihitech/Ursa.Avalonia/assets/20534153/ab86a44a-f92f-43a9-a790-12868f79bbc9)

**Comment by rabbitism** [comment]
这是dialog还是messagebox？

**Comment by nblfeng** [comment]
> 这是dialog还是messagebox？

dialog
