### ISSUE TITLE
MultiComboBox 使用 ClosableTag 关闭标签时若 MultiComboBoxItem不在Popup的可视范围内，MultiComboBoxItem的样式不会取消勾选

### ISSUE THREAD

**Issue by daoyull** [irihitech/Ursa.Avalonia#255]
MultiComboBox 使用 ClosableTag 关闭标签时若 MultiComboBoxItem不在Popup的可视范围内，MultiComboBoxItem的样式不会取消勾选。
1. 勾选若干个Item
<img width="606" alt="step1" src="https://github.com/irihitech/Ursa.Avalonia/assets/86530539/b1613830-9386-494b-9d1f-f6d54c903568">
2. 滚动条向下滚动使前两个Item不在可视范围内
<img width="608" alt="step2" src="https://github.com/irihitech/Ursa.Avalonia/assets/86530539/50986cde-a1b3-4aab-868f-9a0be45cd0eb">
3. 使用ClosableTag 关闭第一个item，第一个MultiComboBoxItem并没有被取消勾选，SelectedItems中的元素已被移除
<img width="590" alt="step3" src="https://github.com/irihitech/Ursa.Avalonia/assets/86530539/bbf1bedb-23e3-434c-96a0-fa9645c9b0ad">

``` csharp
public void Remove(object? o)
    {
        if (o is StyledElement s)
        {
            var data = s.DataContext;
            this.SelectedItems?.Remove(data);
            var item = this.Items.FirstOrDefault(a => ReferenceEquals(a, data));
            if (item is not null)
            {
                var container = ContainerFromItem(item);
                if (container is MultiComboBoxItem t)
                {
                    t.IsSelected = false;
                }
            }
        }
    }
```
断点看了下是不可见的元素在 ContainerFromItem()方法中返回null导致的

**Comment by rabbitism** [comment]
你是通过后台代码取消的还是通过UI操作取消的？

**Comment by daoyull** [comment]
都是通过UI操作的

**Comment by rabbitism** [comment]
不可能呀，因为当你试图点击closable tag的时候popup已经关闭了，再打开popup的时候container都已经重新渲染了

**Comment by daoyull** [comment]
您试试您那边能复现嘛，我在nuget中使用 0.3.0-beta20240518 版本 和 编译最新的代码中都复现了

**Comment by rabbitism** [comment]
我这确实复现不了，如果这个问题很困扰你，而数据量又没有特别大，可以考虑使用非虚拟化的Panel，就是直接设置这个东西的ItemsPanel为StackPanel

**Comment by daoyull** [comment]
换成StackPanel确实解决了问题，但是我对这个不能复现的原因感觉很疑惑，是版本或者其他有不同嘛

**Comment by rabbitism** [comment]
终极原因就是因为虚拟化的container在ContainerFromItem的时候不一定存在，但是我是hack了利用了关闭tag一堆会在popup关闭之后发生，让每次打开popup都能重新realize container。我主要是不知道你在什么情况下可以让关闭tag的同时popup是打开的

**Comment by daoyull** [comment]
我在飞书群组中发了一个有触发过程的视频，版本信息和操作都在里面
