### ISSUE TITLE
`IDialogContext` only work on `CustomDialogControl`

### ISSUE THREAD

**Issue by dameng324** [irihitech/Ursa.Avalonia#256]
https://github.com/irihitech/Ursa.Avalonia/blob/68c55dd331fa25460ed8f307d60cb52407f5b625/src/Ursa/Controls/OverlayShared/OverlayFeedbackElement.cs#L23

This line show the problem. only `CustomDialogControl` is registered.

It's very helpful to support `DefaultDialogControl` to use `IDialogContext` handle dialog's closing.

**Comment by rabbitism** [comment]
yes, we found this issue, will fix in next beta. https://github.com/irihitech/Ursa.Avalonia/issues/243
