### ISSUE TITLE
当我在DataGrid嵌套使用IPv4Box的时候，IPv4Box这个就不能编辑了，OnKeyDown和OnTextInput事件都不会触发

### ISSUE THREAD

**Issue by dandanyouxiang** [irihitech/Ursa.Avalonia#260]
![1](https://github.com/irihitech/Ursa.Avalonia/assets/12132063/820d7363-fe06-4b0a-956e-61990d0ec591)
![GIF](https://github.com/irihitech/Ursa.Avalonia/assets/12132063/63ac2ad3-7f0a-4829-91d5-4a102d56d7d9)

**Comment by rabbitism** [comment]
Maybe we should set the event routing as tunnel.

**Comment by rabbitism** [comment]
I need to postpone this change since any control doesn't work well in 11.0.x will fix after 11.1 finally release.
