### ISSUE TITLE
TagInput 可以增加 Watermark 和 MaxLength 属性吗？

### ISSUE THREAD

**Issue by Soar360** [irihitech/Ursa.Avalonia#266]
Watermark 属性，类似 TextBox ，在输入为空时展示一段提示文本。
MatLength 属性，如果已经输入的数量超过这个值，则不允许输入新的数据。

**Comment by rabbitism** [comment]
MaxLength的问题是当我已经有10个Tag的时候再把MaxLength设置为5意味着什么？

**Comment by Soar360** [comment]
> MaxLength的问题是当我已经有10个Tag的时候再把MaxLength设置为5意味着什么？

个人观点：站在用户的角度看，MaxLength应该只限制手工输入。从客户端提前禁止数据超出范围。但我们不应该丢弃用户的数据。所以，这应该仅仅意味着用户不能输入更多的数据了。至于多出的数据要怎么处理，应该是 ViewMode 或者服务端考虑的事情。
