### ISSUE TITLE
请允许设置UsraWindow窗口右上角的几个小控件禁止获取焦点

### ISSUE THREAD

**Issue by zpf1688** [irihitech/Ursa.Avalonia#277]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/ff9120da-c005-473e-9a02-65aba06864de)
这几个小控件会获取焦点，当用户在表单输入内容时，按Tab键切换输入框，会使得这些控件件获得焦点，这样会让用户不知道发生了什么导致无法输入内容，而且不小心按一下空格键可能就误点击了这些按钮，容易发生意外的情况。
请提供一个方式以便设置右上角的控制组件不能获取焦点。

**Comment by zpf1688** [comment]
此问题我已找到解决方法，就是在Window视图中，设置一个Style，使得Focusable为False即可。
![image](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/ccaaabe5-73c7-4e52-b4ed-fea689798cc0)

**Comment by rabbitism** [comment]
最好使用
```xml
        <Style Selector="u|CaptionButtons Button">
            <Setter Property="Focusable" Value="False"></Setter>
        </Style>
```
