### ISSUE TITLE
Pagination分页控件在PageSizeOptions中切换PageSize后不会触发Command

### ISSUE THREAD

**Issue by nblfeng** [irihitech/Ursa.Avalonia#278]
点击按钮、快速跳转都能触发Command, 但启用ShowPageSizeSelector后, 在切换PaegSize时, 默认不触发Command.
查看了下源码, 在OnPageSizeChanged方法中, 加了InvokeCommand(), 达到预期效果.
![image](https://github.com/irihitech/Ursa.Avalonia/assets/20534153/55abbbb2-2a2b-437b-ae16-be5108803be0)

后续, 还需要解决如何在Command中, 同时获取CurrentPage和PageSize两个参数, 目前我的解决方案是在CommandParameter中传入$self, 但这样似乎不太合理, 还望指教有没有更换的方式~
![image](https://github.com/irihitech/Ursa.Avalonia/assets/20534153/3c798012-ceea-420c-b755-e983f670932c)

**Comment by rabbitism** [comment]
As discussed in qq group, page size change can be monitored in view model.
