### ISSUE TITLE
bug: TreeComboBox控件在第二次展开下级列表时宽度会变窄。

### ISSUE THREAD

**Issue by zpf1688** [irihitech/Ursa.Avalonia#280]
展开一个下级列表后，再展开任何下级列表，下拉列表宽度会自动收缩，如下图：
![image](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/28d62bdb-8730-4ee3-b498-aa7b4aeab986)
![image](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/98b0a24e-1f82-4cb1-aad9-25b4e120ba42)

**Comment by rabbitism** [comment]
暂时不能复现，是Avalonia 11.1.0 rc么？

**Comment by zpf1688** [comment]
11.0.11



---原始邮件---
发件人: "Dong ***@***.***&gt;
发送时间: 2024年7月8日(周一) 凌晨0:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [irihitech/Ursa.Avalonia] bug: TreeComboBox控件在第二次展开下级列表时宽度会变窄。 (Issue #280)




 
暂时不能复现，是Avalonia 11.1.0 rc么？

**Comment by rabbitism** [comment]
Maybe 在新版本中已经修复了，之前ComboBox也有类似的问题，随着popup高度变化，Width失效
https://github.com/irihitech/Semi.Avalonia/issues/124

**Comment by rabbitism** [comment]
Close for now, let me know if you still encountered this issue.
