### ISSUE TITLE
UrsaWindow的内置OverlayDialogHost存在bug。

### ISSUE THREAD

**Issue by WCKYWCKF** [irihitech/Ursa.Avalonia#281]
当你同时创建多个UrsaWindow时，在调用Show的那一刻会返回Cannot register multiple OverlayDialogHost with empty HostId。OverlayDialogHost的实现原理或许需要一些改进，例如针对窗口进行分割查询区等。

**Comment by rabbitism** [comment]
会尽快移除UrsaWindow中内置的DialogHost，还是靠用户自己去注册。用户自己注册的是可以通过赋值ID来实现一个窗口内包含多个host。
