### ISSUE TITLE
0verlayDialog.ShowcustomModal 调用对话框，没有完全实现Modal，焦点仍可以被其他视图获得

### ISSUE THREAD

**Issue by zpf1688** [irihitech/Ursa.Avalonia#282]
![image](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/2486d73b-f516-4061-8ca3-178eda4173dc)
![img_v3_02ci_6f56c797-f4d4-44ab-a90d-e0568089c3ag](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/6f5a8d00-ff37-4ff8-a07d-bc91dd59d0f2)
对话框后面的View中的控件依然可以获得焦点，且能响应按键，只是不能用鼠标点击。用Tab键，就能把焦点移动到被对话框遮挡的控件上。
![img_v3_02ci_7a8d174e-48e3-4f05-beb1-eac7244ccf7g](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/5ecaf7b9-8e14-473d-9e57-0e875f56065a)
多次按Tab键，直到焦点从当前对话框离开，返回了背后的视图中，且可以用键盘操作控件，如输入文本，激活按钮等。
![img_v3_02ci_041ae1fe-9aa7-47f2-b1d5-5003d9e1ebag](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/b30addb6-0ada-4143-9133-3c03da6d8891)
除非使用Window模式才能阻止焦点离开。但使用Window模式对话框时，不能使用MessageBox，因为MessageBox也是一个对话框，和自定义对话框是平级的，导致在弹出MessageBox时，自定义对话框仍能继续操作而无需等待MessageBox关闭，所以可以同时出现多个MessageBox。（如下图）
![img_v3_02ci_1774c487-a00b-452c-88c8-0070395b8e4g](https://github.com/irihitech/Ursa.Avalonia/assets/103982505/1ed25e49-624f-47f2-b406-3ac04c8d4dda)

**Comment by rabbitism** [comment]
虚拟模态是没有办法真正实现模态的

**Comment by rabbitism** [comment]
Two options
1. OverlayDialog在show的时候获取焦点，但这不解决根本问题，因为焦点还是可以回到主窗口
2. 在Show的时候Disable主窗口的其他内容。这是可以交给用户控制的，需要等我重构了OverlayDialogHost的注册逻辑再说

**Comment by zpf1688** [comment]
好吧，暂时我就先麻烦点，在打开对话框之前先把页面上的控件全部禁用

**Comment by rabbitism** [comment]
我对OverlayDiaogHost做了一些修改
1. 允许OverlayDialogHost向上传递自身是否处于Modal状态
2. 开发者始终可以通过对host的modal状态绑定来改变其他控件的属性，比如是不是要enable，是不是要blur。现在主要显示区域可以向上寻找ModalStatusScope的Modal状态来进行这样的绑定。
