### ISSUE TITLE
DateRangePicker的ClearButton不可用，且位置与日历图标重叠

### ISSUE THREAD

**Issue by zpf1688** [irihitech/Ursa.Avalonia#292]
![c3a6e7d06d407ddaf968c7f08e6fb4d2](https://github.com/user-attachments/assets/5461b67e-7203-4ccf-b1db-6d71f6a368ea)

DateRangePicker的ClearButton与日历图标重叠，且点击无反应；
另外，能不能让日历图标也能打开日历选择面板？

**Comment by yangjieshao** [comment]
咦  这个 ClearButton 怎么调出来的 
看代码是隐藏了的啊

**Comment by zpf1688** [comment]
> 咦 这个 ClearButton 怎么调出来的 看代码是隐藏了的啊

Classes="clearButon"
