### ISSUE TITLE
In Windows Server 2019, the style of the dialog box is abnormal

### ISSUE THREAD

**Issue by dotnet9** [irihitech/Ursa.Avalonia#303]
## Alone dialog box

The independent dialog box is shown in the following figure. 1. The border is not displayed, and 2. The content of the title and dialog box user controls is misaligned

![image](https://github.com/user-attachments/assets/d69cd5cb-f14f-42eb-a329-24e14fade373)

## Overlay dialog box

The title and content of the dialog box in the form are displayed incorrectly

![image](https://github.com/user-attachments/assets/226a384a-61d9-46a0-ad91-fef1540b6ed3)

**Comment by rabbitism** [comment]
Closed by https://github.com/irihitech/Ursa.Avalonia/pull/399
