### ISSUE TITLE
功能请求 ： NavMenu添加置底功能

### ISSUE THREAD

**Issue by MakesYT** [irihitech/Ursa.Avalonia#310]
允许一个或多个NavMenuItem置底（常用于设置选项卡）
如下图
![QQ_1721966561795](https://github.com/user-attachments/assets/2492dc85-3171-4f9f-9461-f09baef1f19d)

**Comment by rabbitism** [comment]
有Footer可以放置任意控件

**Comment by MakesYT** [comment]
> 有Footer可以放置任意控件

瞎了，抱歉

**Comment by rabbitism** [comment]
主要是没文档😂

**Comment by MakesYT** [comment]
> 主要是没文档😂

我记得之前不是弄了一个

**Comment by rabbitism** [comment]
> > 主要是没文档😂
> 
> 我记得之前不是弄了一个
> 

辣个是semi的

**Comment by MakesYT** [comment]
> > > 主要是没文档😂
> > 
> > 
> > 我记得之前不是弄了一个
> 
> 辣个是semi的

开一个github page弄文档
