### ISSUE TITLE
控件请求 ： ColorPickerButton

### ISSUE THREAD

**Issue by MakesYT** [irihitech/Ursa.Avalonia#312]
和FA一样
![QQ_1722010802399](https://github.com/user-attachments/assets/8af13dda-3ff2-4fa5-bb96-0cefbe7e7ccb)

**Comment by rabbitism** [comment]
这个有什么特殊的功能么，感觉和Avalonia内置的一样

**Comment by MakesYT** [comment]
> 这个有什么特殊的功能么，感觉和Avalonia内置的一样

这个是类似一个按钮然后点一下会弹出popup来选择颜色，

**Comment by rabbitism** [comment]
> > 这个有什么特殊的功能么，感觉和Avalonia内置的一样
> 
> 这个是类似一个按钮然后点一下会弹出popup来选择颜色，

可以看一下semi demo里的，感觉是一样的

**Comment by MakesYT** [comment]
> > > 这个有什么特殊的功能么，感觉和Avalonia内置的一样
> > 
> > 
> > 这个是类似一个按钮然后点一下会弹出popup来选择颜色，
> 
> 可以看一下semi demo里的，感觉是一样的

原来avalonia自带吗，我一直以为和WPF一样，原来picker是avalonia的view，picker是单独的抱歉

**Comment by rabbitism** [comment]
这个有什么特殊的功能么，感觉和Avalonia内置的一样
