### ISSUE TITLE
Bug: EnumSelector cause crash

### ISSUE THREAD

**Issue by zdpcdt** [irihitech/Ursa.Avalonia#318]
https://github.com/user-attachments/assets/abbd3182-b97e-4162-bb18-2d218695ffd7

EnumSelector `SelectedValue` property:
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

**Comment by rabbitism** [comment]
Closed by #321
