### ISSUE TITLE
希望增加类似主题图标的三态ToggleButton，同时增加可以控制显示的容器

### ISSUE THREAD

**Issue by LiuChao19940201** [irihitech/Ursa.Avalonia#338]
![image](https://github.com/user-attachments/assets/dc237c79-81c3-4ba2-b937-ee2aa9094940)
这种方式显示功能可以实现，但是效果很差

https://github.com/user-attachments/assets/7ec8f655-8633-4d35-a510-541f1873e525

**Comment by rabbitism** [comment]
控制显示的方法你的做法是对的
ToggleButton本就可以三态

**Comment by LiuChao19940201** [comment]
好的，感谢
