### ISSUE TITLE
无法禁用u:UrsaWindow 窗体的双击放大功能？

### ISSUE THREAD

**Issue by LiuChao19940201** [irihitech/Ursa.Avalonia#344]
sRestoreButtonVisible="False"   IsMinimizeButtonVisible="False"都 禁用后，想要窗体禁用双击放大功能

**Comment by rabbitism** [comment]
这个由什么来控制比较好呢，Button的visibility还是CanResize？

**Comment by Soar360** [comment]
在 WinForm 中，如果设置最大化框为 False ，那么就不能最大化了。

**Comment by LiuChao19940201** [comment]
CanResize来控制好一些吧，button还是控制按钮是否显示
