### ISSUE TITLE
UrsaWindow窗体中的全屏按钮，多次放大恢复后，窗体位置会逐渐上移？

### ISSUE THREAD

**Issue by LiuChao19940201** [irihitech/Ursa.Avalonia#345]
https://github.com/user-attachments/assets/36fb5de9-797e-413e-9543-feb7452eb063

全屏后恢复，应该是之前的位置或者每次都回到屏幕正中心位置？

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/15956‘
Need to be fixed from upstream.
