### ISSUE TITLE
ToolBarSeparator无法隐藏

### ISSUE THREAD

**Issue by HandsomeGoldenKnight** [irihitech/Ursa.Avalonia#346]
当使用`<u:ToolBarSeparator IsVisible="False" />`，ToolBarSeparator 无法隐藏

**Comment by rabbitism** [comment]
Separator的可见是由ToolBar来控制的，主要就是为了保证Main的最后一个Separator不能是可见的。在什么情况下需要自己控制他的可见呢？

**Comment by HandsomeGoldenKnight** [comment]
我是想点击ToolBar里的ToggleButton，然后让ToolBar里的其他控件以及控件旁边的ToolBarSeparator 显示

**Comment by rabbitism** [comment]
我没测试过，但你可以尝试把Separator放在一个Panel里面，因为我只控制直接逻辑子元素的IsVisible。
