### ISSUE TITLE
UrsaWindow中showmodal 会把标题栏也盖住，这个有点不合理。。。

### ISSUE THREAD

**Issue by yangf85** [irihitech/Ursa.Avalonia#359]
![image](https://github.com/user-attachments/assets/807a642d-9c8e-4984-878a-7ea94f8b1e23)
如果这个时候想退出程序，做不到

**Comment by LiuChao19940201** [comment]
![image](https://github.com/user-attachments/assets/e8be295f-8a92-43a7-902c-d6ef313cb90b)
是的，我也发现这个问题了，最好是窗体中的Grid默认就从标题栏的下方开始

**Comment by rabbitism** [comment]
UrsaWindow要解决的就是内容侵入TitleBar区域的排版问题。如果不需要内容侵入TitleBar，那么用普通的Window就可以了，Semi设计了相应的样式。
