### ISSUE TITLE
`Locale` doesnt have effect 

### ISSUE THREAD

**Issue by CorrM** [irihitech/Ursa.Avalonia#375]
in my `App.axaml`
```XAML
<Application.Styles>
        <StyleInclude Source="avares://Semi.Avalonia/Themes/Index.axaml" />
        <StyleInclude Source="avares://Semi.Avalonia.DataGrid/Index.axaml" />
        <u-Semi:SemiTheme Locale="en-US" />
    </Application.Styles>
```

Still get Chinese 
![image](https://github.com/user-attachments/assets/aa2da3a5-cf93-458c-b08e-50bfcb3fbba8)

**Comment by CorrM** [comment]
@rabbitism

**Comment by rabbitism** [comment]
Please refer to the latest Semi.Avalonia documentation for the style import method that supports locale. 
https://github.com/irihitech/Semi.Avalonia
```xaml
<Application
    xmlns:semi="https://irihi.tech/semi"
    xmlns:u-semi="https://irihi.tech/ursa/themes/semi">
    <Application.Styles>
        <semi:SemiTheme Locale="en-US" />
        <u-semi:SemiTheme Locale="en-US" />
    </Application.Styles>
</Application>
```

**Comment by CorrM** [comment]
That works thanks.
Can you please edit `Readme.md` file that you need both `semi:SemiTheme` and `u-semi:SemiTheme`
