### ISSUE TITLE
希望增加 MultiComboBox 的 SelectedItems 的排序方式    ItemsSourceOrder |  SelectedOrder

### ISSUE THREAD

**Issue by fzhxhdd888** [irihitech/Ursa.Avalonia#382]

**Comment by rabbitism** [comment]
这个东西最大的问题在于我无法控制用户从外部乱序插入SelectedItems，这样我就不知道我新插入的元素应该插入哪个位置了

**Comment by WCKYWCKF** [comment]
参见：https://docs.avaloniaui.net/zh-Hans/docs/concepts/reactiveui/binding-to-sorted-filtered-list

**Comment by WCKYWCKF** [comment]
SelectedItems每一次的元素变更都会触发排序的话，为什么不直接订阅MultiComboBox.SelectionChanged事件每一次触发都重新给SelectedItems赋一个已排序的值？Items的排序请参阅：https://docs.avaloniaui.net/zh-Hans/docs/concepts/reactiveui/binding-to-sorted-filtered-list。
