### ISSUE TITLE
Dynamic Form generation support

### ISSUE THREAD

**Issue by rabbitism** [irihitech/Ursa.Avalonia#403]
Inspired by #354 

Currently Form Generation from ItemsSource is partially supported. But still needs some improvement:
1. Currently we can only generate FormItem, but not FormGroup
2. User have to manually set label and star in a style
3. ItemTemplate is not taking effect.

These issues should be addressed.

**Comment by kiko-cn** [comment]
Good evening. May I ask when this problem is expected to be solved? Thank you.

**Comment by rabbitism** [comment]
> Good evening. May I ask when this problem is expected to be solved? Thank you.

If you don't need to generate form group, you can already do that. see sample in https://github.com/irihitech/Avalonia-Tutorials/tree/main/Tutorials/Form_Dynamic_Generation 

Since I received no response so I thought this is in low priority.  Will priorities it.
