### ISSUE TITLE
希望能实现PropertyGrid控件

### ISSUE THREAD

**Issue by QinHaifeiCN** [irihitech/Ursa.Avalonia#444]
能否实现wpf toolkit propertygrid 类似功能的控件吗

**Comment by rabbitism** [comment]
https://github.com/bodong1987/Avalonia.PropertyGrid 这个控件库可以兼容各种主题，直接引用这个配合Semi试用就可以了。我们如果实现的话，和这个的功能不会有任何区别。

**Comment by rabbitism** [comment]
暂时关闭，如果有新的提议我再打开。
