### ISSUE TITLE
Pagination控件 切换PageSize后不会触发Command

### ISSUE THREAD

**Issue by manjaoe** [irihitech/Ursa.Avalonia#450]
Pagination控件，切换PageSize后不会触发Command
![PixPin_2024-10-29_18-00-50](https://github.com/user-attachments/assets/5b537606-7d9f-44f9-9d80-df25e3c09b7e)

**Comment by rabbitism** [comment]
Command专用于CurrentPage变化时触发。PageSize变化并不会改变CurrentPage。

**Comment by Soar360** [comment]
当 PageSize 变化时，CurrentPage 也是有可能改变的。比如：变成了 null 。或许，增加一个新的 Command ？
