### ISSUE TITLE
NavigationMenu control parameter bug

### ISSUE THREAD

**Issue by zyknow** [irihitech/Ursa.Avalonia#47]
NavigationMenu look like padding value is to much,
and set closedWith，openWith parameter is not work

![image](https://github.com/irihitech/Ursa.Avalonia/assets/49929368/d918f3cc-915c-4391-b69a-fc76b606f63a)

**Comment by zyknow** [comment]
soorry,is my mistake
 i also want to remove this space,i set CloseWith and OpenWith is not working for
![image](https://github.com/irihitech/Ursa.Avalonia/assets/49929368/d0386db4-7b4c-4a06-80bb-81eeb7b15aa4)

**Comment by rabbitism** [comment]
NavigationMenu is still under development, there may be breaking changes. 
For your screenshot, it is controlled by resource `NavigationMenuClosedWidth`, you can override this.
