### ISSUE TITLE
TagInput 控件绑定到 VM 后，ObservableCollection 有新增，但 Watermark 不消失。

### ISSUE THREAD

**Issue by Soar360** [irihitech/Ursa.Avalonia#478]
如题。

![image](https://github.com/user-attachments/assets/59a2e14c-9645-4279-928e-a7bfb3bfe1a5)

VM

```cshar
public ObservableCollection<String> Size { get; } = new();
```

XAML

```xml
                <u:TagInput
                    Name="SizeTagInput"
                    AllowDuplicates="False"
                    Tags="{Binding Size}"
                    Watermark="输入尺码，按回车添加。" />
```

Command

```csharp
var list = await LoadData();//使用 HTTP 加载数据
foreach(var str in list) this.Size.Add(str);
```

**Comment by rabbitism** [comment]
Can you try to update with dispatcher and see if it works? cannot reproduce.

**Comment by Soar360** [comment]
https://github.com/Soar360/Ursa.Avalonia/tree/main

**Comment by rabbitism** [comment]
Reopen as it is observed even in sync call.

**Comment by rabbitism** [comment]
CheckEmpty should be done directly in `OnCollectionChanged`, otherwise we cannot guarantee if the check is done after collection updated.
