### ISSUE TITLE
Drawer控件对话框无法设置弹出后默认的焦点控件

### ISSUE THREAD

**Issue by KevinL2015** [irihitech/Ursa.Avalonia#479]
我在 overlay modal Drawer对话框控件里用如下代码设置了焦点，发现无效，有没有合适的方法在Drawer对话框出来后使得焦点到某个控件上？
```
UserNameTextBox.AttachedToVisualTree += (_, _) => UserNameTextBox.Focus();
```
看起来是 https://github.com/irihitech/Ursa.Avalonia/pull/316 与这个有关。

**Comment by rabbitism** [comment]
可以尝试下在loaded之后再focus？

**Comment by rabbitism** [comment]
> 大佬好快的速度。
> 
> 也不行，dawer出来时有个动画，loaded里设置也无效，看起来是我的代码设置之后，又再次被设置了，但是不知道设置到哪里去了。

那下个版本尽量出一个fix

**Comment by KevinL2015** [comment]
辛苦了！

测试demo里Drawer，看上去焦点尝试给DefaultDrawerControl的Border去了（Name="PART_Root"）
![image](https://github.com/user-attachments/assets/f17b9d10-1c96-4207-b6f1-801b288922a5)
![image](https://github.com/user-attachments/assets/f68dc9b7-3808-458b-a57b-65358841d956)

**Comment by KevinL2015** [comment]
我在代码里加了样式，把PART_Root的Focusable改成false了，焦点就正常了，但我不确定有没有其他副作用。
```
<Style Selector="u|CustomDrawerControl /template/ Border#PART_Root.Shadow">
    <Setter Property="Focusable" Value="False" />
</Style>
```

**Comment by rabbitism** [comment]
> 我在代码里加了样式，把PART_Root的Focusable改成false了，焦点就正常了，但我不确定有没有其他副作用。
> 
> ```
> <Style Selector="u|CustomDrawerControl /template/ Border#PART_Root.Shadow">
>     <Setter Property="Focusable" Value="False" />
> </Style>
> ```

主要作用是让模态对话框真的处于模态状态，保证焦点不会泄漏到主窗口的内容，对于你这个case因为你确保有其他的焦点，所以不会有什么问题，但是不能保证其他Dialog都有焦点。
