### ISSUE TITLE
Pagination: index out of range and Content switch trigger

### ISSUE THREAD

**Issue by tobeforever** [irihitech/Ursa.Avalonia#50]
I use the Pagination in my project,and I found a BUG.When I switch PageSize, it triggers a recalculation of CurrentPage.In UpdateButtons, sometimes index is passed in greater than TotalCount, so it is necessary to check if index is greater than TotalCount when assigning the currentIndex field.
Here are my suggestions:

```C#
 private void UpdateButtons(int index)
    {
        if (_buttonPanel is null) return;
        if (PageSize == 0) return;

        // old
        int currentIndex = index;

        // new
        int currentIndex = index <= TotalCount ? index : TotalCount;
        ......
//
```

Also, when I use Pagination in my project, I need to refresh the page content when the CurrentPage and PageSize properties change. Since Pagination doesn't have event and command bindings, I need to do a page refresh trigger in the set method of the PageSize and CurrentPage bound properties.
When I switch PageSize, the CurrentPage property changes and then the PageSize property changes, which causes my page to refresh repeatedly. Is there any good way to deal with it?
Maybe we can add a Command here,and Execute Command when the property changed.

**Comment by rabbitism** [comment]
I really doubt if I should update CurrentPage when page size changed.. I think this should be controlled by user.
