### ISSUE TITLE
希望增加文字滚动样式和翻牌时钟样式

### ISSUE THREAD

**Issue by 763305292** [irihitech/Ursa.Avalonia#502]
类似滚动公告那样, 文字滚动前方可以自定义图标最好了.
翻牌时钟类似:
<img width="179" alt="1733391650591" src="https://github.com/user-attachments/assets/706ac2bf-867f-4a4b-9a58-931f66ec8cf0">

**Comment by rabbitism** [comment]
文字滚动已经实现。 #514 

翻盘时钟不在计划之内。
