### ISSUE TITLE
Avalonia 微信群申请加入

### ISSUE THREAD

**Issue by heartacker** [irihitech/Ursa.Avalonia#51]
你好，在哔哩看到说可以私信你，可以邀请加入 微信 Avalonia 群，
麻烦拉我入群可以吗，谢谢

**Comment by rabbitism** [comment]
![1691912759848.jpg](https://github.com/irihitech/Ursa.Avalonia/assets/14807942/0ce51d6c-6a83-4b8d-9b4e-5bddc8fd4fff)

加这位拉你进群
