### ISSUE TITLE
关于Navigation控件的体验问题

### ISSUE THREAD

**Issue by bus1nessman** [irihitech/Ursa.Avalonia#52]
您好，首先Ursa的方向一定是好的，功能也是急的，未来也能给刚接触avalonia的人一个全新的体验。
希望能继续加油！！！
然后是关于Navigation导航的一些意见，在体验上不够流畅，有明显的卡顿和转场动效比较突兀，希望能有更好的体验

**Comment by rabbitism** [comment]
突然发现我上周回复发送失败了……
首先感谢您的支持。
目前Navigation（以及其他若干没有开发的控件）都面临一个问题，就是子控件换Visual Parent的问题。在设计上，如果使用MVVM是没有问题，但如果同时支持inline控件就会有很大问题，我还在想这有没有什么比较general的解决办法……

**Comment by rabbitism** [comment]
Should be fixed in #105
