### ISSUE TITLE
关于 Drawer.ShowCustom 不显示问题

### ISSUE THREAD

**Issue by anguszou** [irihitech/Ursa.Avalonia#524]
**界面：**
<Grid Grid.Column="1" ClipToBounds="True">
	<Border
        BorderBrush="{DynamicResource SemiGrey1}"
        Background="{DynamicResource SemiColorBackground1}"
        BorderThickness="1"
        ClipToBounds="True"
        CornerRadius="20">
		<u:OverlayDialogHost HostId="LocalHost"/>
	</Border>
</Grid>

**ViewModels：**
var options = new DrawerOptions()
{
    Position = Position.Right,
    Buttons = DialogButton.None,
    CanLightDismiss = false,
    IsCloseButtonVisible = true,
    Title="库存明细",
    CanResize = false,
};
var hostId = IsLocal ? "LocalHost" : null;
var vm = new StockDetailsViewModel();
await Drawer.ShowModal<StockDetailsControl, StockDetailsViewModel>(vm, hostId, options);

**Program：**
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UseManagedSystemDialogs()
        .UsePlatformDetect()
        .With(new Win32PlatformOptions())
        .LogToTrace();

代码能够顺利执行到 await Drawer.ShowModal  且无异常信息，界面无法正常显示抽屉 想问问是我代码存在bug，还是缺少什么配置

**Comment by rabbitism** [comment]
IsLocal 为true吗？

**Comment by anguszou** [comment]
IsLocal 为false

**Comment by rabbitism** [comment]
IsLocal为False那么他就会去找没有ID的OverlayDialogHost，这个只在UrsaWindow是默认内置的，如果不用UrsaWindow那么就要自己放一个没有ID的OverlayDialogHost

**Comment by anguszou** [comment]
可以了，非常感谢 OverlayDialogHost放置的位置不太对 导致没有显示完全
